//
//  Color+Extension.swift
//  BetaBuddy
//
//  Design System - Color Utilities
//  Note: Color definitions are auto-generated from Asset Catalog
//

import SwiftUI

// MARK: - Hex Initializer

extension Color {
    /// Initialize Color from a hex string
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 3: // RGB (12-bit)
            (a, r, g, b) = (255, (int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6: // RGB (24-bit)
            (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        case 8: // ARGB (32-bit)
            (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(
            .sRGB,
            red: Double(r) / 255,
            green: Double(g) / 255,
            blue: Double(b) / 255,
            opacity: Double(a) / 255
        )
    }
}

// MARK: - Design System Color Reference
/*
 Colors are defined in Assets.xcassets and auto-generated by Xcode:
 
 - Color.betaBlue: #4DD0E1 - Brand Primary
 - Color.cruxNavy: #1A2B45 - Brand Secondary
 - Color.sendOrange: #FF9F1C - Action/Accent
 - Color.backgroundBase: #F4F8F9 - Background
 - Color.surfaceCard: #FFFFFF - Cards
 - Color.textPrimary: #1A2B45 - Primary text
 - Color.textSecondary: #607D8B - Secondary text
 */
